language: 'ko-KR'
early_access: false

reviews:
  profile: 'chill' # 'chill', 'strict', 'balanced' 등 선택 가능
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true # PR 생성 시 자동 리뷰
    drafts: false # draft PR은 자동 리뷰하지 않음

chat:
  auto_reply: true # PR에 질문하면 자동 응답 (예: 코드 설명해달라고 코멘트 남기면 답함)
