import { ROUTES } from '@routes/routes-config';

export const NO_HEADER_PATHS = [
  ROUTES.MATCH_CREATE,

  ROUTES.LOGIN,

  ROUTES.ERROR,

  ROUTES.LOADING,
  ROUTES.SIGNUP,

  ROUTES.ONBOARDING,
  ROUTES.ONBOARDING_GROUP,
];

export const SHOW_BOTTOM_NAVIGATE_PATHS = [ROUTES.HOME, ROUTES.MATCH, ROUTES.CHAT, ROUTES.PROFILE];