
export const iconNames = [
  'arrow-left-18',
  'arrow-left-24',
  'arrow-left-white',
  'arrow-left',
  'arrow-right',
  'baseball',
  'calendar-16',
  'calendar',
  'caution',
  'chat-filled',
  'chat-lined',
  'chat-profile',
  'check-filled',
  'cheer-team',
  'clock',
  'close',
  'empty',
  'error-filled',
  'female',
  'gender',
  'group-role',
  'home-filled',
  'home-lined',
  'indicator',
  'info-filled',
  'kakao-logo',
  'location',
  'logo-gray',
  'logo',
  'male',
  'matching',
  'matchinglist-filled',
  'matchinglist-lined',
  'my-filled',
  'my-lined',
  'plus',
  'team',
  'watching'
] as const;
 
export type IconName = (typeof iconNames)[number];
