// ✅ This file is auto-generated by generate-icon-list.ts
export const iconNames = [
  'ic-arrow-left-18',
  'ic-arrow-left-24',
  'ic-arrow-left-white',
  'ic-arrow-left',
  'ic-arrow-right',
  'ic-baseball',
  'ic-calendar',
  'ic-caution',
  'ic-chat-filled',
  'ic-chat-lined',
  'ic-check-filled',
  'ic-clock',
  'ic-error-filled',
  'ic-home-filled',
  'ic-home-lined',
  'ic-info-filled',
  'ic-kakao-logo',
  'ic-location',
  'ic-matchinglist-filled',
  'ic-matchinglist-lined',
  'ic-my-filled',
  'ic-my-lined',
  'ic-plus',
  'ic-x',
  'logo-gray',
  'logo'
] as const;
 
export type IconName = typeof iconNames[number];
