export const iconNames = [
  'graphic-cheer-team',
  'graphic-empty',
  'graphic-gender',
  'graphic-group-role',
  'graphic-matching',
  'graphic-team',
  'graphic-watching',
  'chat-profile',
  'ic-arrow-left-18',
  'ic-arrow-left-24',
  'ic-arrow-left-white',
  'ic-arrow-left',
  'ic-arrow-right',
  'ic-baseball',
  'ic-calendar-16',
  'ic-calendar',
  'ic-caution',
  'ic-chat-filled',
  'ic-chat-lined',
  'ic-check-filled',
  'ic-clock',
  'ic-error-filled',
  'ic-female',
  'ic-home-filled',
  'ic-home-lined',
  'ic-indicator',
  'ic-info-filled',
  'ic-kakao-logo',
  'ic-location',
  'ic-male',
  'ic-matchinglist-filled',
  'ic-matchinglist-lined',
  'ic-my-filled',
  'ic-my-lined',
  'ic-plus',
  'ic-x',
  'logo-gray',
  'logo',
<<<<<<< HEAD
  'profile',
=======
>>>>>>> 205c8c7 (chore: 충돌해결(#83))
] as const;

export type IconName = (typeof iconNames)[number];
