import fs from 'node:fs';
import path from 'node:path';

const iconsDir = path.resolve(__dirname, '../assets/svgs/sprites');
const outputPath = path.resolve(__dirname, '../icon-list.ts');

const iconFiles = fs.readdirSync(iconsDir).filter((file) => file.endsWith('.svg'));

const iconNames = iconFiles.map((file) => `"${file.replace('.svg', '')}"`);

const content = `// ✅ This file is auto-generated by scripts/generate-icon-list.ts
export const iconList = [
  ${iconNames.join(',\n  ')}
] as const;

export type IconName = typeof iconList[number];
`;

fs.writeFileSync(outputPath, content);
console.log(`✅ icon-list.ts generated with ${iconNames.length} icons.`);
