export const ROUTES = {
  LAYOUT: '/',
  HOME: '/',
  AUTH: '/auth',
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/onboarding',
  ONBOARDING_GROUP: '/onboarding/group',
  GAME: (date = ':date', gameId = ':gameId') => `/game/${date}/${gameId}`,
  MATCH_CREATE: (id = ':matchId') => `/match/create/${id}`,
  MATCH_SINGLE: (id = ':matchId') => `/match/single/${id}`,
  GROUP_MATES: (id = ':matchId') => `/match/groups/mates/${id}`,
  GROUP_NEW: (id = ':matchId') => `/match/groups/${id}/new`,
  MATCH: '/match',
  MATCH_MEMBER_DETAIL: (
    matchId: number | string = ':matchId',
    memberId: number | string = ':memberId',
  ) => `/match/${matchId}/members/${memberId}`,
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  CHAT: '/chat',
  CHAT_ROOM: '/chatroom',
  RESULT: (id = ':matchId') => `/result/${id}`,
  ERROR: '/error',
  LOADING: '/loading',
  SPLASH: '/splash',
  GUIDE: '/guide',
};
